### ISSUE TITLE
I cannot get the MTUtils.setBlockDrops to work

### ISSUE THREAD

**Issue by Boter316** [LionZXY/MTUtils#5]
I tried this script

MTUtils.setBlockDrops(<AWWayofTime:boundPickaxe> harvester, <Avaritia:Resource_Block:1> block, <TConstruct:toolShard:501> [9]);

and it keeps saying 
ERROR: Error parsing Extra Stuff.zs:85 -- ) expected

I have tried everything for the past few days and cannot figre out how to make this damn thing work, there are no examples anywhere and so I have nothing to base it off of

please give me an example of how this works... please...

**Comment by LionZXY** [comment]
Where you get this nameid? It's wrong nameid. Use this:
```
 /mt hand
```

**Comment by Boter316** [comment]
I figured out the problem, feel free to close this
